# Generated by Django 5.1.7 on 2025-04-23 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forum_title_forumvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='tag',
            field=models.CharField(choices=[('ikan', 'Ikan'), ('kolam', 'Kolam'), ('siklus', 'Siklus'), ('budidayaplus', 'BudidayaPlus')], default='ikan', max_length=12),
        ),
    ]
