# Generated by Django 5.1.7 on 2025-04-17 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_forumvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='forum',
            name='title',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
