# Generated by Django 5.1.6 on 2025-05-07 15:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_tag'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumvote',
            name='vote_choice',
        ),
    ]
