# Generated by Django 5.1.6 on 2025-04-26 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0003_forum_tag'),
        ('forum', '0003_forum_title'),
    ]

    operations = [
    ]
