# Generated by Django 5.1.6 on 2025-03-19 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("fish_death", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="fishdeath",
            old_name="sampling_id",
            new_name="id",
        ),
        migrations.AlterField(
            model_name="fishdeath",
            name="fish_alive_count",
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name="fishdeath",
            name="fish_death_count",
            field=models.IntegerField(),
        ),
    ]
