# Generated by Django 5.1.7 on 2025-03-22 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_death', '0002_rename_sampling_id_fishdeath_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdeath',
            name='fish_alive_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='fishdeath',
            name='fish_death_count',
            field=models.IntegerField(default=0),
        ),
    ]
