# Generated by Django 5.1.7 on 2025-03-24 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_death', '0003_alter_fishdeath_fish_alive_count_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fishdeath',
            name='fish_alive_count',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='fishdeath',
            name='fish_death_count',
            field=models.IntegerField(),
        ),
    ]
