# Generated by Django 5.1.6 on 2025-03-21 02:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fish_sampling', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fishsampling',
            name='fish_dead',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
