# Generated by Django 5.1.7 on 2025-04-21 16:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fish_sampling', '0002_fishsampling_fish_dead'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fishsampling',
            name='fish_dead',
        ),
    ]
