name: SonarCloud CI
on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest
    continue-on-error: true
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.12
      if: always()
      uses: actions/setup-python@v3
      with:
        python-version: 3.12
    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install coverage
    - name: Run Migrations
      run: python manage.py migrate
    - name: Run Tests with Coverage
      run: |
        coverage run manage.py test
        coverage xml

  sonarcloud:
    needs: build-test
    continue-on-error: true
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: SonarCloud Scan
      if: always()
      uses: SonarSource/sonarcloud-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
      with:
        args: >
          -Dsonar.organization=${{ secrets.SONAR_ORGANIZATION_KEY }}
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }}
          -Dsonar.python.version=3.12
          -Dsonar.sources=.
          -Dsonar.python.coverage.reportPaths=coverage.xml
          -Dsonar.exclusions=**/migrations/**,**/tests/**,**/venv/**